image: ros:melodic-ros-core

stages:
  - build
  - test

cache:
  paths:
    - build/
    - devel/

before_script:
  - apt update >/dev/null && apt install -y git >/dev/null
  - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git >/dev/null
  - source ros_gitlab_ci/gitlab-ci.bash >/dev/null
  - apt-get install -y libopencv-dev

# catkin build camera_cone_detection:
#  stage: build
#  script:
#    - catkin build sgtdv_msgs --summarize --no-status --force-color --catkin-make-args run_tests
#    - catkin build camera_cone_detection --summarize --no-status --force-color --catkin-make-args run_tests
#    - catkin_test_results # Check if one of the tests failed!

catkin build lidar_cone_detection:
  stage: build
  script:
    - catkin build sgtdv_msgs --summarize --no-status --force-color --catkin-make-args run_tests
    - catkin build lidar_cone_detection --summarize --no-status --force-color --catkin-make-args run_tests
    - catkin_test_results # Check if one of the tests failed!

catkin build fusion:
  stage: build
  script:
    - catkin build sgtdv_msgs --summarize --no-status --force-color --catkin-make-args run_tests
    - catkin build fusion --summarize --no-status --force-color --catkin-make-args run_tests
    - catkin_test_results # Check if one of the tests failed!

catkin build jetson_can_interface:
  stage: build
  script:
    - catkin build sgtdv_msgs --summarize --no-status --force-color --catkin-make-args run_tests
    - catkin build jetson_can_interface --summarize --no-status --force-color --catkin-make-args run_tests
    - catkin_test_results # Check if one of the tests failed!

catkin build path_planning:
  stage: build
  script:
    - catkin build sgtdv_msgs --summarize --no-status --force-color --catkin-make-args run_tests
    - catkin build path_planning --summarize --no-status --force-color --catkin-make-args run_tests
    - catkin_test_results # Check if one of the tests failed!

catkin build path_tracking:
  stage: build
  script:
    - catkin build sgtdv_msgs --summarize --no-status --force-color --catkin-make-args run_tests
    - catkin build path_tracking --summarize --no-status --force-color --catkin-make-args run_tests
    - catkin_test_results # Check if one of the tests failed!

catkin build pose_estimate:
  stage: build
  script:
    - catkin build sgtdv_msgs --summarize --no-status --force-color --catkin-make-args run_tests
    - catkin build pose_estimate --summarize --no-status --force-color --catkin-make-args run_tests
    - catkin_test_results # Check if one of the tests failed!

catkin build slam:
  stage: build
  script:
    - catkin build sgtdv_msgs --summarize --no-status --force-color --catkin-make-args run_tests
    - catkin build slam --summarize --no-status --force-color --catkin-make-args run_tests
    - catkin_test_results # Check if one of the tests failed!

# catkin build all:
#  stage: build
#  script:
#    - catkin build --summarize --no-status --force-color
#   artifacts:
#     paths:
#       - 'catkin_workspace/build'
#       - 'catkin_workspace/devel'

# catkin test all:
#  stage: test
#  script:
#   - catkin run_tests --no-status --force-color
#   - catkin_test_results # Check if one of the tests failed!
#   artifacts:
#     paths:
#       - 'catkin_workspace/build'
#       - 'catkin_workspace/devel'
