#define SGT_VISUALIZATION
#define SGT_TESTING
//#define CAMERA_DETECTION_CARSTATE
//#define CAMERA_DETECTION_CAMERA_SHOW
//#define CAMERA_DETECTION_FAKE_LIDAR
//#define CAMERA_DETECTION_CONSOLE_SHOW
//#define CAMERA_DETECTION_RECORD_VIDEO
//#define CAMERA_DETECTION_RECORD_VIDEO_SVO //malo by sa skusit s kamerou
#define DEBUG_STATE
